version: "3"
services:
  nginx:
    image: nginx:1.18.0
    ports:
      - "80:80"
    restart: always
    volumes:
      - "../nginx/nginx.conf:/etc/nginx/nginx.conf"
  redis-server:
    image: "redis"
    restart: always
    container_name: redis
  node-app:
    build: ./
    restart: always
    container_name: node
    ports:
      - "4000:4000"
