version: "3"
services:
  nginx:
    image: nginx:1.18.0
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ../server:/usr/share/nginx/html
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../certbot-etc:/etc/letsencrypt
  redis-server:
    image: "redis"
    restart: always
    container_name: redis
  node-app:
    build: ./
    restart: always
    container_name: node
    ports:
      - "4000:4000"
  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ../server:/usr/share/nginx/html
      - ../certbot-etc:/etc/letsencrypt
    command: certonly --dry-run --webroot --webroot-path=/usr/share/nginx/html --email yoteamo7@naver.com --agree-tos --no-eff-email --keep-until-expiring -d bogobogo.shop -d www.bogobogo.shop
