version: "3"
services:
  redis-server:
    image: "redis"
    restart: always
    container_name: redis
  node-app:
    build: ./
    restart: always
    container_name: node
    ports:
      - "4000:4000"
