-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgIY8oMDJEtGmjT5EV
FC95FfzAdBWD6ncan8XlD/oZYMqgCgYIKoZIzj0DAQehRANCAATy1d+VZjtoEWSk
kRgpqMdtoY9araNv9ZmcOmUMI6p0NA60N299utmOIePKg+mz/KtNHMTEGG5eatf7
gpcfsDup
-----END PRIVATE KEY-----